FROM php:7.1-fpm

ENV TZ=Asia/Shanghai

RUN apt-get update ; apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev; \
        docker-php-ext-install -j$(nproc) iconv mcrypt pdo pdo_mysql zip; \
        docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/;\
        docker-php-ext-install -j$(nproc) gd;\
        apt-get purge -y --auto-remove \
        -o APT::AutoRemove::RecommendsImportant=false \
        -o APT::AutoRemove::SuggestsImportant=false; \
        rm -rf /var/cache/apt/*; \
        rm -rf /var/lib/apt/lists/*;

COPY ./php.conf /usr/local/etc/php/conf.d/php.conf
COPY ./html /var/www/html
